name: Testing Branch

on:
  pull_request:
    branches: [ testing ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    env:
      DB_CONNECTION: sqlite
      DB_DATABASE: database/database.sqlite

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v2

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.ci', '.env');"

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Start Redis
      uses: supercharge/redis-github-action@1.4.0
      
    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Compile assets
      run: |
        npm install
        npm run production

    - name: Optimize
      run: php artisan optimize

    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: ECS
      run: vendor/bin/ecs check

    - name: Psalm
      run: vendor/bin/psalm --show-info=false --no-cache

    - name: Phpstan
      run: ./vendor/bin/phpstan analyse

    - name: Migrations
      run: php artisan migrate:fresh --seed

    # - name: Routes
    #   run: php artisan route:list

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit
